version: "3.6"

services:
  producer:
    build:
        context: .
        dockerfile: Dockerfile-producer
    networks:
      - outside
    container_name: producer
    ports:
        - 8000:8000
    command: gunicorn producer:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
  consumer:
    build:
        context: .
        dockerfile: Dockerfile-consumer
    networks:
      - outside
    container_name: consumer
    command: python3 consumer.py

networks:
  outside:
    external:
      name: tutorial